context("box-colors.R")

test_that("box_docs_color returns correct color", {
  res1 <- box_docs_color(0)
  res2 <- box_docs_color(1)
  res3 <- box_docs_color(NULL)
  expect_equal(res1, "red")
  expect_equal(res2, "green")
  expect_equal(res3, "red")
})

test_that("box_meta_color returns correct color", {
  res1 <- box_meta_color(0)
  res2 <- box_meta_color(1)
  res3 <- box_meta_color(2)
  res4 <- box_meta_color(3)
  res5 <- box_meta_color(4)
  res6 <- box_meta_color(NULL)
  expect_equal(res1, "red")
  expect_equal(res2, "orange")
  expect_equal(res3, "orange")
  expect_equal(res4, "green")
  expect_equal(res5, "green")
  expect_equal(res6, "red")
})

test_that("box_success_color returns correct color", {
  res1 <- box_success_color(0)
  res2 <- box_success_color(25)
  res3 <- box_success_color(49)
  res4 <- box_success_color(50)
  res5 <- box_success_color(51)
  res6 <- box_success_color(75)
  res7 <- box_success_color(89)
  res8 <- box_success_color(90)
  res9 <- box_success_color(91)
  res10 <- box_success_color(100)
  res11 <- box_success_color(NULL)
  expect_equal(res1, "red")
  expect_equal(res2, "red")
  expect_equal(res3, "red")
  expect_equal(res4, "red")
  expect_equal(res5, "orange")
  expect_equal(res6, "orange")
  expect_equal(res7, "orange")
  expect_equal(res8, "green")
  expect_equal(res9, "green")
  expect_equal(res10, "green")
  expect_equal(res11, "red")
})
