default:
  app_url: "https://shinypro.synapse.org/users/awilliams/dccmonitor-test/"
  production: TRUE
  consortium_fileview: "syn21027019"
  samples_table: "syn21578908"
  annotations_storage: "syn21703007"
  annotations_table: "syn10242922"
  annotations_link: "https://shinypro.synapse.org/users/nkauer/amp-ad-metadata-dictionary/"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  teams:
    - "273957"
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      human: "syn12973252"
      mouse or other animal model: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "syn12973256"
      proteomics: "syn12973255"
  species_list:
    - "mouse or other animal model"
    - "human"
    - "drosophila"
  complete_columns:
    manifest:
      - "parent"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"

dev:
  production: FALSE

amp-ad:
  app_url: "https://shinypro.synapse.org/users/awilliams/dccmonitor/"
  annotations_link: "https://shinypro.synapse.org/users/nkauer/amp-ad-metadata-dictionary/"
  consortium_fileview: "syn21448475"
  samples_table: "syn21578908"
  annotations_storage: "syn21698384"
  annotations_table: "syn21459391"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  teams:
    - "3346847"
  species_list:
    - "human"
    - "drosophila"
    - "MODEL-AD mouse model"
    - "other mouse or animal model"
  templates:
    individual_templates:
      human: "syn12973254"
      other mouse or animal model: "syn12973253"
      MODEL-AD mouse model: "syn21084071"
    biospecimen_templates:
      human:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      other mouse or animal model:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      MODEL-AD mouse model:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      drosophila: "syn20673251"
    assay_templates:
      ATACseq: "syn22024364"
      autorad: "syn22087295"
      immunoassay: "syn22117582"
      proteomics: "syn12973255"
      single cell RNAseq: "syn21018360"
      wholeGenomeSeq: "syn21018358"
      wholeExomeSeq: "syn21078272"
      NanoString: "syn21082744"
      snpArray: "syn21372586"
      STARRSeq: "syn26125115"
      TMT quantitation: "syn21433357"
      methylationArray: "syn22036881"
      MRI: "syn22087332"
      PET: "syn22087299"
      16SrRNAseq: "syn24184375"
      metabolomics: "syn24216748"
      HI-C: "syn25671270"
      ChIPSeq: "syn22907810"
      bisulfiteSeq: "syn25830897"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"

pec:
  app_url: "https://shinypro.synapse.org/users/kmontgomery/dccmonitor/"
  samples_table: "syn22175287"
  annotations_table: "syn20981788"
  annotations_storage: "syn21763155"
  annotations_link: "https://www.synapse.org/#!Synapse:syn20729790"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  consortium_fileview: "syn21560413"
  teams:
    - "3328037"
  templates:
    manifest_template: "syn20782058"
    individual_templates:
      human: "syn20781820"
      animal: "syn21053116"
    biospecimen_templates:
      human:
        in vivo, postmortem, other: "syn20768131"
        in vitro: "syn26011297"
      other mouse or animal model:
        in vivo, postmortem, other: "syn20768131"
        in vitro: "syn26011297"
    assay_templates:
      ATACSeq: "syn20768526"
      bisulfiteSeq: "syn23017098"
      ChIPSeq: "syn21861858"
      HI-C: "syn21680758"
      immunoassay: "syn25805392"
      methylationArray: "syn25805391"
      rnaSeq: "syn20768650"
      snpArray: "syn21680759"
      STARRSeq: "syn26011215"
      TMT quantitation: "syn21680761"
      wholeGenomeSeq: "syn20980993"
  species_list:
    - "human"
    - "animal model"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
    individual:
      - "individualID"
      - "individualIdSource"
      - "species"
      - "reportedGender"
      - "postmortem"
      - "primaryDiagnosis"
    biospecimen:
      - "individualID"
      - "specimenID"
      - "organ"
      - "tissue"
      - "nucleicAcidSource"
    assay:
      - "specimenID"
      - "platform"
      - "libraryPrep"
      - "libraryPreparationMethod"
      - "runType"

1kD:
  app_url: "https://shinypro.synapse.org/users/danlu/dccmonitor_1kD/"
  samples_table: "syn27817789"
  annotations_table: "syn27806892"
  annotations_storage: "syn27605404"
  annotations_link: "https://www.synapse.org/#!Synapse:syn27817580"
  annotation_keys:
    - "age"
    - "primaryDiagnosis"
  consortium_fileview: "syn27646655"
  teams:
    - "3433360"
  templates:
    manifest_template: "syn27832372"
    individual_templates:
      human: "syn29358381"
    biospecimen_templates:
      human: "syn29358373"
    assay_templates:
  species_list:
    - "human"
  complete_columns:
    manifest:
      - "path"
      - "parent"
      - "fileFormat"
      - "program"
      - "project"
      - "study"
      - "resourceType"
    individual:
      - "program"
      - "project"
      - "study"
      - "individualID"
      - "householdID"
      - "person"
      - "sex"
      - "noOfChildren"
      - "noOfAdults"
      - "spokenLanguage"
    biospecimen:
      - "program"
      - "project"
      - "study"
      - "person"
      - "individualID"
      - "specimenID"
      - "specimenType"
      - "samplingAge"
      - "samplingAgeUnits"
